---
default_language_version:
    python: python3
default_stages:
    - prepare-commit-msg
    - commit
    - push
    - post-commit
exclude: ^$
fail_fast: true
repos:
    - repo: https://github.com/psf/black
      rev: 20.8b1
      hooks:
          - id: black
    - repo: https://gitlab.com/pycqa/flake8
      rev: 3.8.4
      hooks:
          - id: flake8
            additional_dependencies:
                - flake8-bugbear
    - repo: https://github.com/PyCQA/bandit
      rev: 1.7.0
      hooks:
          - id: bandit
            args:
                - -ll
            files: .py$
    - repo: https://github.com/PyCQA/isort
      rev: 5.6.4
      hooks:
          - id: isort
    - repo: https://github.com/PyCQA/pydocstyle
      rev: 5.1.1
      hooks:
          - id: pydocstyle
    - repo: https://github.com/codespell-project/codespell
      rev: v2.0.0
      hooks:
          - id: codespell
    - repo: https://github.com/asottile/reorder_python_imports
      rev: v2.3.6
      hooks:
          - id: reorder-python-imports
            args:
                - --py3-plus
    - repo: https://github.com/pre-commit/mirrors-mypy
      rev: v0.790
      hooks:
          - id: mypy
    - repo: https://github.com/asottile/dead
      rev: v1.3.0
      hooks:
          - id: dead
    - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
      rev: 0.1.0
      hooks:
          - id: yamlfmt
          # args: [--mapping, '2', --sequence, '4', --offset, '2']
    - repo: git://github.com/adrienverge/yamllint
      rev: v1.25.0
      hooks:
          - id: yamllint
            files: \.(yaml|yml)$
            types: [file, yaml]
            exclude: pyproject.toml
            entry: yamllint --strict
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v3.4.0
      hooks:
          # - id: no-commit-to-branch
          #   args:
          #       - --branch
          #       - master
          #   always_run: true
          - id: check-added-large-files
          - id: check-ast
          - id: check-case-conflict
          - id: check-docstring-first
          - id: check-executables-have-shebangs
          - id: check-merge-conflict
            stages:
                - commit
          - id: check-added-large-files
            stages:
                - commit
          - id: trailing-whitespace
            stages:
                - commit
          - id: mixed-line-ending
            stages:
                - commit
          - id: check-executables-have-shebangs
            stages:
                - commit
          - id: check-json
          - id: check-merge-conflict
          - id: check-symlinks
          - id: check-toml
          - id: check-vcs-permalinks
          - id: check-xml
          - id: check-yaml
          - id: detect-aws-credentials
            args:
                - --allow-missing-credentials
          - id: fix-byte-order-marker
          - id: fix-encoding-pragma
          - id: detect-private-key
          - id: end-of-file-fixer
          - id: fix-byte-order-marker
          - id: fix-encoding-pragma
          - id: mixed-line-ending
          - id: pretty-format-json
            args:
                - --autofix
          - id: name-tests-test
          - id: trailing-whitespace
            args:
                - --markdown-linebreak-ext=md
    - repo: https://github.com/asottile/pyupgrade
      rev: v2.7.4
      hooks:
          - id: pyupgrade
            args:
                - --py37-plus
    - repo: https://github.com/Lucas-C/pre-commit-hooks-safety
      rev: v1.1.3
      hooks:
          - id: python-safety-dependencies-check
            args:
                - check
                - --full-report
    - repo: https://github.com/mattlqx/pre-commit-sign
      rev: v1.1.3
      hooks:
          - id: sign-commit
    - repo: https://github.com/IamTheFij/docker-pre-commit
      rev: v2.0.0
      hooks:
          - id: docker-compose-check
          - id: hadolint
    - repo: https://github.com/thoughtworks/talisman
      rev: v1.11.0
      hooks:
          - id: talisman-commit
          - id: talisman-push
    - repo: local
      hooks:
          - id: py.test
            name: py.test
            language: python
            additional_dependencies:
                - pytest
                - pytest-cov
                - coverage
                - fuzzywuzzy
                - python-Levenshtein
            entry: pytest -v
            require_serial: true
            pass_filenames: false
            files: \.py$
